### ISSUE TITLE
Add HVSHELFLOC to  item_mapping.json

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/folio_migration#41]
@jermnelson could you add HVSHELFLOC to the item_mapping.json. It should map to a folio item note called HVSHELFLOC. (Description = Hooover staff note)

Related to https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/170 

This should be done before we reload data if possible. 

Thanks!

**Comment by jermnelson** [comment]
@ahafele double-checking in Airflow, we're already creating the HVSHELFLOC item note at https://github.com/sul-dlss/libsys-airflow/blob/2215e9caf38bae25fed58c30c021fe8c1dc74b71/plugins/folio/items.py#L44-L47 so it isn't mapped in the item_mapping.json. I think we can close this issue.

**Comment by jermnelson** [comment]
@ahafele and @dlrueda Just an update after investigating catkey `a14182559` with item barcode `36105075597216`. The item JSON record had the HVSHELFLOC note but with an empty `itemNoteTypeId`:

```json
 [{'note': 'B10.MOLD.014.01.C',
   'staffOnly': True,
   'itemNoteTypeId': None}]
```

This was caused because HVSHELFLOC was the 11th item-note-type and the default limit is 10. Fixed in this PR https://github.com/sul-dlss/libsys-airflow/pull/208
